# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths: ['module/sample/go/*']
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Track location where file is changed
      run:
        files=(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA)
        echo $files
     
    - name: Install dependencies
      run: go get ./module/sample/go/
      
    - name: Test
      run: go test -v ./module/sample/go
